# 1L0Gx Configuration (sample)
# NOTE: Prefer configuring via environment variables in production:
#   TIDB_HOST, TIDB_PORT, TIDB_USER, TIDB_PASSWORD, TIDB_DATABASE
#   LLM_PROVIDER, LLM_API_KEY, LLM_MODEL

tidb:
  host: "localhost"       # or your TiDB host
  port: 4000
  user: "root"
  password: "changeme"
  database: "test"

llm:
  provider: "groq"
  api_key: ""
  model: "llama-3.1-8b-instant"
